---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nvidia
description: wipos Nvidia

base-image: ghcr.io/ublue-os/bluefin-dx-nvidia
image-version: stable

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/repo/fedora-%OS_VERSION%/jstaf-onedriver-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/manciukic/libfprint-tod-goodix/repo/fedora-%OS_VERSION%/manciukic-libfprint-tod-goodix-fedora-%OS_VERSION%.repo
    install:
      - https://github.com/bitwarden/clients/releases/download/desktop-v2025.1.1/Bitwarden-2025.1.1-x86_64.rpm
      - libfprint-tod-goodix
      - nextdns
      - onedriver
      - proton-vpn-gnome-desktop
    remove:
      - libfprint

  - type: default-flatpaks
    notify: false # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - io.github.zen_browser.zen

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
