# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nvidia
description: wipos Nvidia

base-image: ghcr.io/ublue-os/bluefin-dx-nvidia
image-version: latest

modules:
  # yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
  - type: files
    files:
      - source: system
        destination: /
  # yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/repo/fedora-%OS_VERSION%/jstaf-onedriver-fedora-%OS_VERSION%.repo
    install:
      - onedriver
      - proton-vpn-gnome-desktop
      - nextdns
    remove:
  # yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
      remove:
  # yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

